### ISSUE TITLE
Split

### ISSUE THREAD

**Issue by ortizbnu** [rodrigomafei/Ebanx.net#1]
Boa noite
Alguma previsão de ter o split ?

**Comment by alexandresanlim** [comment]
Nossa equipe esta trabalhado exatamente com isso no momento, acredito que em breve o split estará implementado. O @rodrigomafei  pode te posicionar melhor.

**Comment by rodrigomafei** [comment]
@ortizbnu  Já foi implementando a algum tempo, de uma olhada na classe PaymentRequest, ela possui uma lista com as splites
